routes/admin.php
<?php
Route::get('/home', 'Admin\\AdminController@home')->name('admin.home');
Route::get('/', 'Admin\\AdminController@home')->name('admin.home');

Route::match(['get', 'post'], '/chpassword', 'Admin\\AdminController@changePassword');

Route::group(['middleware' => ['auth'], 'rols' => ['settings' => ['update']]], function () {
    Route::match(['get', 'post'], '/settings', 'Admin\AdminController@appSettings');
});


/** Posts Route  */
Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['read']],
              'page'       => ['page' => ['read']],
              'blog'       => ['blog' => ['read']],
              'course'     => ['course' => ['read']]
             ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['index']]);
});

Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['create']],
              'page'       => ['page' => ['create']],
              'blog'       => ['blog' => ['create']],
              'course'     => ['course' => ['create']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['create']]);
});

Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['create']],
              'page'       => ['page' => ['create']],
              'blog'       => ['blog' => ['create']],
              'course'     => ['course' => ['create']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['store']]);
});

Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['update']],
              'page'       => ['page' => ['update']],
              'blog'       => ['blog' => ['update']],
              'course'     => ['course' => ['update']]
             ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['edit']]);
});

Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['update']],
              'page'       => ['page' => ['update']],
              'blog'       => ['blog' => ['update']],
              'course'     => ['course' => ['update']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['update']]);
});

Route::group(['middleware' => ['auth'], 
              'service'    => ['service' => ['delete']],
              'page'       => ['page' => ['delete']],
              'blog'       => ['blog' => ['delete']],
              'course'     => ['course' => ['delete']]
          ], function () {
    Route::resource('/posts', 'Admin\PostController', ['only' => ['destroy']]);
});

// Route::group(['middleware' => ['auth']], function () {
//     Route::patch('/posts/toggle_status/{post}', 'Admin\PostController@toggleStatus');
// });


/** Categories Route  */
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['read']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['index']]);
});
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['create']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['create']]);
});
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['create']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['store']]);
});
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['update']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['edit']]);
});
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['delete']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['destroy']]);
});
Route::group(['middleware' => ['auth'], 'rols' => ['category' => ['update']]], function () {
    Route::resource('/categories', 'Admin\CategoryController', ['only' => ['update']]);
});


/** Admins Route  */
Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['read']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['index']]);
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['create']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['create']]);
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['create']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['store']]);
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['update']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['edit']]);
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['delete']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['destroy']]);
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['update']]], function () {
    Route::patch('/admins/toggle_status/{admin}', 'Admin\AdminController@toggleStatus');
});

Route::group(['middleware' => ['auth'], 'rols' => ['admin' => ['update']]], function () {
    Route::resource('/admins', 'Admin\AdminController', ['only' => ['update']]);
});

Route::get('getcounts', 'Admin\\AdminController@getCounts');
Route::get('clients', 'Admin\\AdminController@clients');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/banners', 'Admin\BannerController');
    Route::resource('/counters', 'Admin\CountersController');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Guest Available Routes */
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');

Route::get('/pg/{page_key}', 'FrontController@page')->name('page');
Route::get('/services/{category}', 'FrontController@services')->name('services');
Route::get('/service/{service}', 'FrontController@service')->name('service');
Route::get('/contact', 'FrontController@contact')->name('contect');
Route::get('/blog', 'FrontController@blog')->name('blog');
Route::get('/post/{post}', 'FrontController@post')->name('post');

Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
});
Route::post('/servicemail', 'FrontController@servicemail')->name('servicemail');
Route::post('/contactmail', 'FrontController@contactmail')->name('contactmail');



/** Admin Auth Routes */
Route::get('admin/login', 'V1\Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'V1\Auth\AdminLoginController@login')->name('admin.login.submit');

Route::get('admin/reset', 'V1\Auth\AdminLoginController@resetPassword')->name('admin.reset');
Route::post('admin/reset', 'V1\Auth\AdminLoginController@resetPassword')->name('admin.reset.submit');
// Route::get('admin/register', 'V1\Auth\AdminRegisterController@showRegistrationForm')->name('admin.register');
// Route::post('admin/register', 'V1\Auth\AdminRegisterController@register')->name('admin.register.submit');
Route::post('admin/logout', 'V1\Auth\AdminLoginController@logout')->name('admin.logout');

app/Models/Common/Post.php
<?php

namespace App\Models\Common;

use App;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = "posts";

    protected $guarded = [];

    public function postCategory()
    {
        return $this->belongsTo(Category::class, 'category', 'id');
    }

    public function getTitleAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'title_'.$local };
    }

    public function getContentAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'content_'.$local };
    }

    public function getShortDescAttribute()
    {
    	$local = App::getLocale();
        return $this->{ 'short_desc_'.$local };
    }
}

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Common\Post;
use App\Models\Common\Banner;
use App\Models\Common\Counters;
use App\Models\Common\Category;
use App\Models\Client\Client;

use App;
use DB;
use Illuminate\Support\Facades\Mail;
use App\Mail\RegisterMail;

class FrontController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
     {
    //     $locale = App::getLocale();
    //     echo $locale;
    //     exit();
        $ishome     = 1;
        $banners    = Banner::get();
        $counters   = Counters::get();
        $posts      = Post::where('post_type', 'blog')->latest()->limit(3)->get();
        /*$about      = About::find(1);
        $categories = Categories::where('in_home', '=', 1)->get();
        $services   = Service::get();
        $posts      = Posts::limit(3)->latest()->get();
        $works      = Works::limit(3)->latest()->get();
        $team       = Counters::get();
        $logos      = Integration::get();*/
        ////
        return view('front.home')->with(compact('ishome', 'banners', 'about', 'posts', 'counters'));
    }

    public function page($page_key)
    {
        $bkg = rand(1,8);
        $pages = [
                    'who_we_are' => 1, 
                    'why_us' => 2, 
                    'payments' => 3,
                    'privacy_policy' => 4,
                    'service_agreement' => 5
                 ];
        $data = Post::find($pages[$page_key]);
        $counters       = Counters::get();
        return view('front.page')->with(compact('data', 'counters', 'bkg'));
    }

    public function contact()
    {
        $bkg = rand(1,8);
        return view('front.contact')->with(compact('bkg'));
    }

    public function services(Category $category)
    {
        $bkg = rand(1,8);
        return view('front.services')->with(compact('category', 'bkg'));
    }

    public function service(Post $service)
    {
        $bkg = rand(1,8);
        return view('front.service')->with(compact('service', 'bkg'));
    }

    public function joinus()
    {
        $top_slider_img = 'slider-img-Joinus';
        return view('front.joinus')->with(compact('top_slider_img'));
    }

    public function blog()
    {
        $bkg = rand(1,8);
        $posts = Post::where('post_type', 'blog')->orderBy('updated_at', 'DESC')->get();
        return view('front.blog')->with(compact('posts', 'bkg'));
    }

    public function post(Post $post)
    {
        $bkg = rand(1,8);
        $posts = Post::where('post_type', 'blog')
                     ->where('id', '!=', $post->id)->orderBy('updated_at', 'DESC')->limit(5)->get();
        return view('front.blogpost')->with(compact('posts', 'post', 'bkg'));
    }

    public function servicemail(Request $request){

        $typ = $request->typ;

        $appSettings = DB::table('settings')->select(['app_form_email'])->where('id', 1)->first();
        $toMail = $appSettings->app_form_email;

        if($typ == 'service')
        {
            $title  = $request->title;
            $data = ['title' => $title, 'email' => $request->email, 'name' => $request->name, 'phone' => $request->phone, 'message' => $request->message];

            $mail = Mail::send('emails.service', ['data' => $data], function ($m) use ($toMail, $title) {
                $m->to($toMail)->subject($title.' - Service Request!');
            });
             $dataClient = [
                            'name'  => $request->name,
                            'email' => $request->email,
                            'phone' => $request->phone
                          ];
            try{
                Client::firstOrCreate(['email' => $request->email], $dataClient);
            }catch(Exception $e){}

        }
        else if($typ == 'contact')
        {
            $subject = $request->title;
            $data = ['email' => $request->email, 'name' => $request->name, 'phone' => $request->phone, 'subject' => $subject, 'message' => $request->message];
            $mail = Mail::send('emails.contact', ['data' => $data], function ($m) use ($toMail, $subject) {
                $m->to($toMail)->subject('Web Contact Form');
            });
        }
        


        //if($mail) {
            $msgStatus = 1;
        //}
        return response()->json([
            'status' => $msgStatus
        ]);
    }

    public function contactmail(Request $request){

        $appSettings = DB::table('settings')->select(['app_form_email'])->where('id', 1)->first();
        $toMail = $appSettings->app_form_email;

        $subject = $request->title;

        $data = ['email' => $request->email, 'name' => $request->name, 'phone' => $request->phone, 'subject' => $subject, 'message' => $request->message];
        print_r($data);
        exit();
        $mail = Mail::send('emails.contact', ['data' => $data], function ($m) use ($toMail, $subject) {
            $m->to($toMail)->subject('Web Contact Form');
        });

        return response()->json([
            'status' => 1
        ]);
    }
}

resources/views/front/blog.blade.php
@extends('front.front')

@section('content')
<section class="hero-wrap hero-wrap-2" style="background-image: url({{ asset('public/images/bg_'.$bkg.'.jpg') }});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">@lang('front.blog')</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{{ url('/') }}">@lang('front.home') <i class="ion-ios-arrow-forward"></i></a></span> <span>@lang('front.blog') </span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section bg-light">
      <div class="container">
        <div class="row">
          @foreach($posts as $post)
          <div class="col-md-6 col-lg-4 ftco-animate">
            <div class="blog-entry">
              <a href="{{ url('/post/'.$post->id) }}" class="block-20 d-flex align-items-end" style="background-image: url({{ $post->image ? asset($post->image) : asset('public/images/no-photo.png') }});">
                <div class="meta-date text-center p-2">
                  <span class="day">{{ Carbon::parse($post->updated_at)->format('d') }}</span>
                  <span class="mos">{{ Carbon::parse($post->updated_at)->format('M') }}</span>
                  <span class="yr">{{ Carbon::parse($post->updated_at)->format('Y') }}</span>
                </div>
              </a>
              <div class="text bg-white p-4">
                <h3 class="heading"><a href="{{ url('/post/'.$post->id) }}">{{ $post->title }}</a></h3>
                <p>{{ $post->short_desc ?? '.....' }}</p>
                <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="{{ url('/post/'.$post->id) }}" class="btn btn-primary">@lang('front.more')</a></p>
                  
                </div>
              </div>
            </div>
          </div>
          @endforeach
        </div>
        <!-- <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div> -->
      </div>
    </section>
@stop

resources/views/front/blogpost.blade.php
@extends('front.front')

@section('content')
<section class="hero-wrap hero-wrap-2" style="background-image: url({{ asset('public/images/bg_'.$bkg.'.jpg') }});">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">{{ $post->title }}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{{ url('/') }}">@lang('front.home') <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{{ url('/blog') }}">@lang('front.blog') <i class="ion-ios-arrow-forward"></i></a></span> <span>{{ $post->title }} </span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 ftco-animate">
            <h2 class="mb-3">{{ $post->title }}</h2>
            @if($post->image)
            <p>
              <img src="{{ asset($post->image) }}" alt="" class="img-fluid">
            </p>
            @endif
            {!! $post->content !!}
          </div> <!-- .col-md-8 -->

          <div class="col-lg-4 sidebar ftco-animate">
            <div class="sidebar-box ftco-animate">
              <h3>@lang('front.recent')</h3>
              @foreach($posts as $post)
              <div class="block-21 mb-4 d-flex">
                <a href="{{ url('/post/'.$post->id) }}" class="blog-img mr-4" style="background-image: url({{ $post->image ? asset($post->image) : asset('public/images/no-photo.png') }});"></a>
                <div class="text">
                  <h3 class="heading"><a href="{{ url('/post/'.$post->id) }}">{{ $post->title }}</a></h3>
                  <div class="meta">
                    <div><a href="{{ url('/post/'.$post->id) }}"><span class="icon-calendar"></span> {{ Carbon::parse($post->updated_at)->format('d m Y') }}</a></div>
                  </div>
                </div>
              </div>
              @endforeach
            </div>
          </div><!-- END COL -->
        </div>
      </div>
    </section>
@stop

resources/views/front/home.blade.php
@extends("front.front")
@section("content")
	<section class="home-slider owl-carousel" style="direction: ltr;">
      @foreach($banners as $banner)
      <div class="slider-item" style="background-image:url({{ url($banner->image) }});">
        <div class="overlay"></div>
        <div class="container">
          <div class="row no-gutters slider-text align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-7 ftco-animate">
            @if($banner->short_desc)
            <span class="subheading">{{ $banner->short_desc }}</span>
            @endif

            @if($banner->title)
            <h1 class="mb-4">{{ $banner->title }}</h1>
            @endif
            <!-- <p><a href="#" class="btn btn-primary px-4 py-3 mt-3">Our Services</a></p> -->
          </div>
        </div>
        </div>
      </div>
      @endforeach
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row d-flex">
          <div class="col-md-5 order-md-last wrap-about align-items-stretch">
            <div class="wrap-about-border ftco-animate">
              <div class="img" style="background-image: url(images/about.jpg); border"></div>
              <div class="text">
                <h3>Read Our Success Story for Inspiration</h3>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word.</p>
                <p><a href="#" class="btn btn-primary py-3 px-4">Contact us</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-7 wrap-about pr-md-4 ftco-animate">
            <h2 class="mb-4">Our Main Features</h2>
            <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word.</p>
            <div class="row mt-5">
              <div class="col-lg-6">
                <div class="services active text-center">
                  <div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-collaboration"></span></div>
                  <div class="text media-body">
                    <h3>Organization</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
                  </div>
                </div>
                <div class="services text-center">
                  <div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-analysis"></span></div>
                  <div class="text media-body">
                    <h3>Risk Analysis</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
                  </div>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="services text-center">
                  <div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-search-engine"></span></div>
                  <div class="text media-body">
                    <h3>Marketing Strategy</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
                  </div>
                </div>
                <div class="services text-center">
                  <div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-handshake"></span></div>
                  <div class="text media-body">
                    <h3>Capital Market</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <section class="ftco-intro ftco-no-pb img" style="background-image: url({{ asset('public/images/bg_6.jpg') }}">
        <div class="container">
          <div class="row justify-content-center mb-5">
            <div class="col-md-10 text-center heading-section heading-section-white ftco-animate">
              <h2 class="mb-0">@lang('front.guidance')</h2>
            </div>
          </div>  
        </div>
      </section>

    <section class="ftco-counter" id="section-counter">
        <div class="container">
          <div class="row d-md-flex align-items-center justify-content-center">
            <div class="wrapper">
              <div class="row d-md-flex align-items-center">
                @foreach($counters as $counter)
                <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
                  <div class="block-18">
                    <div class="icon"><span class="flaticon-doctor"></span></div>
                    <div class="text">
                      <strong class="number" data-number="{{ $counter->count }}">0</strong>
                      <span>{{ $counter->title }}</span>
                    </div>
                  </div>
                </div>
                @endforeach
              </div>
            </div>
          </div>
        </div>
      </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">
            <h2 class="mb-4">@lang('front.services')</h2>
            
          </div>
        </div>
        <div class="row no-gutters">

          @foreach($appCategories as $category)
            <div class="col-lg-4 d-flex">
              <a href="{{ url('/services/'.$category->id) }}">
                <div class="services-2 {{ ($loop->index == 0 ||  $loop->index % 3 == 0) ? 'noborder-left' : '' }}  text-center ftco-animate">
                  <div class="icon mt-2 d-flex justify-content-center align-items-center"><span class="flaticon-analysis"></span></div>
                  <div class="text media-body">
                    <h3>
                      @if($share_locale == 'ar')
                        {{ $category->name_ar }}
                      @else
                        {{ $category->name_en }}
                      @endif
                    </h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia.</p>
                  </div>
                </div>
              </a>
            </div>
          @endforeach
        </div>
      </div>
  </section>
    


    <section class="ftco-section ftco-consult ftco-no-pt ftco-no-pb" style="background-image: url({{ asset('public/images/bg_8.jpg') }}" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-md-12 py-5 px-md-5">
            <div class="py-md-5">
              <div class="heading-section heading-section-white ftco-animate mb-5">
                <h2 class="mb-4">@lang('front.request_quote')</h2>
                
              </div>
              <form action="#" class="appointment-form ftco-animate">
                <div class="d-md-flex">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="{{ __('front.name') }}" id="quote_name">
                  </div>
                  <div class="form-group ml-md-4">
                    <input type="text" class="form-control" placeholder="{{ __('front.email') }}"  id="quote_email">
                  </div>
                </div>
                <div class="d-md-flex">
                  <div class="form-group">
                    <div class="form-field">
                      <div class="select-wrap">
                        <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                        <select name="" id="quote_service" class="form-control">
                          <option value="0" style="color: #afafaf">----- {{ __('front.select_service') }} -----</option>
                          @foreach($appServices as $service)
                            <option value="{{ $service->title_en }}">
                                @if($share_locale == 'ar')
                                  {{ $service->title_ar }}
                                @else
                                  {{ $service->title_en }}
                                @endif
                            </option>
                          @endforeach
                          <option value="Other">{{ __('front.other_service') }}</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="form-group ml-md-4">
                    <input type="text" class="form-control" placeholder="{{ __('front.phone') }}" id="quote_phone">
                  </div>
                </div>
                <div class="d-md-flex">
                  <div class="form-group">
                    <textarea name="" id="quote_message" cols="30" rows="2" class="form-control" placeholder="{{ __('front.message') }}"></textarea>
                  </div>
                  <div class="form-group ml-md-4">
                    <input type="button" onclick="servicemail('contact')" value="{{ __('front.request_quote') }}" class="btn btn-white py-3 px-4">
                  </div>

                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

  <section class="ftco-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">
            <h2 class="mb-4">@lang('front.blog')</h2>
          </div>
        </div>
        <div class="row">
          @foreach($posts as $post)
          <div class="col-md-6 col-lg-4 ftco-animate">
            <div class="blog-entry">
              <a href="{{ url('/post/'.$post->id) }}" class="block-20 d-flex align-items-end" style="background-image: url({{ $post->image ? asset($post->image) : asset('public/images/no-photo.png') }});">
                <div class="meta-date text-center p-2">
                  <span class="day">{{ Carbon::parse($post->updated_at)->format('d') }}</span>
                  <span class="mos">{{ Carbon::parse($post->updated_at)->format('M') }}</span>
                  <span class="yr">{{ Carbon::parse($post->updated_at)->format('Y') }}</span>
                </div>
              </a>
              <div class="text bg-white p-4">
                <h3 class="heading"><a href="{{ url('/post/'.$post->id) }}">{{ $post->title }}</a></h3>
                <p>{{ $post->short_desc ?? '.....' }}</p>
                <div class="d-flex align-items-center mt-4">
                  <p class="mb-0"><a href="{{ url('/post/'.$post->id) }}" class="btn btn-primary">@lang('front.more')</a></p>
                  
                </div>
              </div>
            </div>
          </div>
          @endforeach
        </div>
      </div>
  </section>
@endsection